name: Mark stale issues and PRs

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has gone stale due to inactivity."
          stale-pr-message: "This PR has gone stale."
          stale-issue-label: stale
          stale-pr-label: stale
          days-before-stale: 14
          days-before-close: 7
          exempt-issue-labels: pinned,discussion,on hold
          exempt-pr-labels: pinned,discussion,on hold
